
package s19.raid;

// A Raid1 uses a group of disks to simulate a more reliable one. Every disk
// is intended to have the same contents. It is not a problem if some members
// are broken, provided that there is at least one which is still working.
// A Raid1 with 5 members will be more reliable than a Raid1 with 3 members.

// This skeleton has been automatically generated by IntelliJ IDEA...
// Please verify/adapt everything!

public class Raid1 extends Raid {

  public Raid1(DiskDevice[] members) {
    super(members);
  }

  @Override
  public int capacity() {
    // the parent class knows the common capacity among all disk members
    return 0; // TODO
  }

  @Override
  public byte readAt(int index) throws DeadDiskException, InvalidIndexException {
    // We try to redirect the operation on the members, until we find one which
    // was able to perform it
    return 0; // TODO
  }

  @Override
  public void writeAt(int index, byte data) throws DeadDiskException, InvalidIndexException {
    // We must redirect the operation on every member able to perform it.
    // In case none was responding, then this Raid1 is now dead itself
    // TODO
  }
}